spring.application.name=api-gateway
spring.cloud.gateway.server.webflux.routes[0].id=citizen-health-profile-service
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/healthGov/**
spring.cloud.gateway.server.webflux.routes[0].uri=lb://citizen-health-profile-service