# ===============================
# Application Basics
# ===============================
spring.application.name=api-gateway

server.port=9091

# ===============================
# JWT Configuration
# ===============================
jwt.secret=ECeR4KSw5vhsigaezz97kOAZNb2BKXWKh0XDP1PKWG53mPdBOqtkrtsGxOt3ouxQSko3yQRQ04ADMpk1hlFqEC

# ===============================
# Config Server (Optional)
# ===============================
spring.config.import=optional:configserver:http://localhost:1234

# ===============================
# Eureka Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===============================
# Spring Security (Disable Default User)
# ===============================
spring.security.user.name=disabled
spring.security.user.password=disabled

# ===============================
# Logging (Gateway Debug)
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
logging.level.reactor.netty.http.server=DEBUG

# ===============================
# Gateway Routes
# ===============================

# Research Service - Research APIs
spring.cloud.gateway.server.webflux.routes[0].id=research-service-research
spring.cloud.gateway.server.webflux.routes[0].uri=lb://research-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/research/**

# Research Service - Manager APIs
spring.cloud.gateway.server.webflux.routes[1].id=research-service-manager
spring.cloud.gateway.server.webflux.routes[1].uri=lb://research-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/manager/**

# Auth Service
spring.cloud.gateway.server.webflux.routes[2].id=auth-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/healthGov/**

# Auth Service - Audit Logs
spring.cloud.gateway.server.webflux.routes[3].id=auth-service-audit
spring.cloud.gateway.server.webflux.routes[3].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/audit_log/**

# Citizen Health Profile Service
spring.cloud.gateway.server.webflux.routes[4].id=citizen-health-profile-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://citizen-health-profile-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/citizen/**,/health-profile/**

# Infrastructure Service
spring.cloud.gateway.server.webflux.routes[5].id=infrastructure-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://infrastructure-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/infrastructures/**

# Resource Service
spring.cloud.gateway.server.webflux.routes[6].id=resource-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://resource-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/resources/**

# Health Program Service - Programs -Enrollements
spring.cloud.gateway.server.webflux.routes[7].id=health-program-service-programs
spring.cloud.gateway.server.webflux.routes[7].uri=lb://health-program-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/programs/**,/api/enrollments/**

# Compliance & Audit Service
spring.cloud.gateway.server.webflux.routes[8].id=compliance-audit-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://compliance-audit-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/audits/**,/api/v1/compliance-records/**

spring.cloud.gateway.server.webflux.routes[9].id=notification-alerts-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://notification-alerts-service
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/notifications/**
