spring.application.name=api-gateway
server.port=9091
jwt.secret=ECeR4KSw5vhsigaezz97kOAZNb2BKXWKh0XDP1PKWG53mPdBOqtkrtsGxOt3ouxQSko3yQRQ04ADMpk1hlFqEC
# api-gateway application.properties
spring.security.user.name=disabled
spring.security.user.password=disabled

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/healthGov/**
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service

spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/audit_log/**
spring.cloud.gateway.server.webflux.routes[1].uri=lb://auth-service