spring.application.name=citizen-health-profile-service
spring.datasource.url=jdbc:mysql://localhost:3306/healthgov_db?createDatabaseIfNotExist=true

spring.config.import=optional:configserver:http://localhost:1234

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
server.port=6789