spring.application.name=reporting-analytics-service

spring.datasource.url=jdbc:mysql://localhost:3306/reports_db?createDatabaseIfNotExist=true
spring.config.import=optional:configserver:http://localhost:1234

server.port=4050