spring.application.name=health-program-service

server.port=4500

eureka.client.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/health_program_MSP_db?createDatabaseIfNotExist=true
spring.datasource.password=2110

spring.config.import=optional:configserver:http://localhost:1234



management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always