spring.application.name=compliance-audit-service

server.port=5050

spring.datasource.url=jdbc:mysql://localhost:3306/compliance_audit_db?createDatabaseIfNotExist=true
spring.datasource.password=Vikki@CTS01!!

spring.config.import=optional:configserver:http://localhost:1234

logging.file.name=logs/Compliance-Audits.log

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always


logging.level.feign=DEBUG
logging.level.com.healthgov.feignclients=DEBUG
