spring.application.name=config-server
#server.port=1234
spring.cloud.config.server.git.uri=https://github.com/PRATAP0070/HealthGovConfigServer.git
server.port=1234
#spring.cloud.config.server.git.uri=https://github.com/Pavankumar-955/config-server-repo.git
spring.cloud.config.server.git.skip-ssl-validation=true

#optional but recommmened
#spring.cloud.config.server.git.clone-on-start=true